Added chromedriver 126.0.6478.126
webdriverextensions/webdriverextensions-maven-plugin-repository pull request #118
Opened 2024-07-10 19:14 UTC by EpicVoyage

2024-07-13 09:12 UTC, treyturner requested changes

2024-07-13 09:12 UTC, treyturner commented on repository-3.0.json
> +        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/win32/chrome-win32.zip",
We need the `chromedriver` binary as opposed to `chrome`
```suggestion
        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/win32/chromedriver-win32.zip",
```

2024-07-13 09:12 UTC, treyturner commented on repository-3.0.json
> +        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/win64/chrome-win64.zip",
```suggestion
        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/win64/chromedriver-win64.zip",
```

2024-07-13 09:12 UTC, treyturner commented on repository-3.0.json
> +        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/mac-x64/chrome-mac-x64.zip",
```suggestion
        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/mac-x64/chromedriver-mac-x64.zip",
```

2024-07-13 09:12 UTC, treyturner commented on repository-3.0.json
> +        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/mac-arm64/chrome-mac-arm64.zip",
```suggestion
        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/mac-arm64/chromedriver-mac-arm64.zip",
```

2024-07-13 09:12 UTC, treyturner commented on repository-3.0.json
> +        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chrome-linux64.zip",
```suggestion
        	"url": "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chromedriver-linux64.zip",
```

2024-07-13 09:29 UTC, treyturner commented
This is blocked by #119

2024-07-13 09:30 UTC, treyturner approved these changes

2024-07-21 14:32 UTC, sephiroth-j commented
I have removed the old version of edgedriver and updated the branch. I think it is now ready to be merged.

2024-07-26 11:43 UTC, merged